
###.................
# 1. Demographic-----
###.................

###.................
## 1.1 Base population-----
###.................

pop0 <- readRDS(file=paste0(paste0(wd_proc,"PopProjectionCol2050.rds")))

pop0 <- pop0[ANO==Tstart,]

###.................
## 1.1 nfx-----
###.................

###.................
## 1.2 nqx-----
###.................


#CFc is the cause-specific transition probability 
#from sick to dead from cause c 

#BGmx,t is the cause-specific transition from sick to dead from any non-c cause 


###.................
## 1.3 Leslie-----
###.................


###.................
# 2. Epidemiologic-----
###.................

###.................
## 2.1 prevalence-----
###.................




###.................
## 2.2 incidence-----
###.................

#IRc is the transition from well to sick (incidence) from that cause

###.................
# 3. Economic-----
###.................

###.................
## 3.1 Costs-----
###.................
